### ISSUE TITLE
test data set

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Server.Java#13]
Small question, are you using a test data set to check if the LDF server works as expected ? If not, I can throw in a DCAT-ish demo set with about 100K triples and write some tests.

**Comment by mielvds** [comment]
I use an HDT file to test stuff, but no real unit-tests The NodeJS implementation has a lot of them though, so they are definitely welcome here.

**Comment by barthanssens** [comment]
'kay, first attempt is in pull request

**Comment by mielvds** [comment]
Thanks! I had to correct the illegal URI characters { and }, please make sure your Turtle/NT fields are correct. Merged.
