### ISSUE TITLE
Upgrade to Jena 3.01

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Server.Java#17]
Sort of reminder, I guess it also means working on upgrading Jena in the HDT library (https://github.com/rdfhdt/hdt-java)

**Comment by mielvds** [comment]
Fortunately, this was already done for https://github.com/rdfhdt/hdt-java/issues/2.
The upgrade to jena 3.0.0 is now in branch jena-3, but you need the RDFHDT build from branch [hdt-jena-3.0.0](https://github.com/rdfhdt/hdt-java/tree/hdt-jena-3.0.0)
