### ISSUE TITLE
Maven artifact

### ISSUE THREAD

**Issue by hartig** [LinkedDataFragments/Server.Java#20]
Any chance to make this project available as an artifact in an online Maven repository?

**Comment by mielvds** [comment]
Would Sonatype be a good fit? Maven central does not accept new projects anymore due to scalability issues. http://central.sonatype.org/pages/ossrh-guide.html

**Comment by hartig** [comment]
I don't see any issue with using Sonatype.

**Comment by mielvds** [comment]
Alright, new release was issued in [v0.1.0](https://github.com/LinkedDataFragments/Server.Java/releases/tag/v0.1.0). Maven repository request is pending: https://issues.sonatype.org/browse/OSSRH-19942

**Comment by RubenVerborgh** [comment]
Thank you, @mielvds, this is great!

**Comment by mielvds** [comment]
Now available at https://search.maven.org/#artifactdetails%7Corg.linkeddatafragments%7Cldfserver%7C0.1.0%7Cwar
