### ISSUE TITLE
Extract Query object

### ISSUE THREAD

**Issue by mielvds** [LinkedDataFragments/Server.Java#21]
In order to access the selector of the fragment, a structured object would be nice (e.g., the triple pattern of the requested TPF). Also, for instance, to build the HTML views. Of course, this should be flexible enough to fit all LDFs besides TPFs.

@hartig : since you started the refactoring, any proposals on this?

**Comment by hartig** [comment]
Sounds like a reasonable thing to do. I might give it a try if I find some time during the holidays.

In any case, I think an important requirement for such a "TriplePatternSelector" class (and other types of selectors) is that this class should be API-independent; i.e., it should not depend on some RDF API such as Jena (a Jena-specific subclass would be possible of course). The rationale for this requirement is in one of my earlier comments: https://github.com/LinkedDataFragments/Server.Java/pull/19#issuecomment-164889889

**Comment by hartig** [comment]
I am working on it.

**Comment by mielvds** [comment]
Fixed with #22 . Thanks, HTML views are coming up.
