### ISSUE TITLE
"views" directory must be duplicated in downstream projects

### ISSUE THREAD

**Issue by hartig** [LinkedDataFragments/Server.Java#32]
While pulling in the new online Maven artifact into downstream projects works great (thanks again @mielvds!), the current implementation of views makes it impossible to run an LDF server developed in such a downstream project without duplicating files. For instance, if I want to run my Blazegraph-based TPF server, I have to retrieve the "views" directory (from https://github.com/LinkedDataFragments/Server.Java/tree/master/views) and copy this into my project directory. Without doing this, the servlet throws a FileNotFoundException in which it complains that `/home/olaf/BlazegraphBasedTPFServer/views does not exist.`

Is there a way to integrate the views directory into the package that can be retrieved via Maven?

**Comment by mielvds** [comment]
I moved all classes and resources to the default `src/main`, which includes all assets and views in the assembly jar. See https://github.com/LinkedDataFragments/Server.Java/commit/38d68b68f559b429c67599c3672da36f9472262f

Could you verify this repo locally?

**Comment by mielvds** [comment]
Or with v0.1.1: https://search.maven.org/#artifactdetails%7Corg.linkeddatafragments%7Cldfserver%7C0.1.1%7Cwar

**Comment by hartig** [comment]
Miel, I would love to test it but I cannot get it compiled because the test classes are not available any more in the `ldfserver-0.1.1.jar` (they are in `ldfserver-0.1.0.jar`, and they are needed for BlazegraphBasedTPFServer). Any change to get them back in?

**Comment by mielvds** [comment]
Ah shoot, this maven thing is way too confusing and vague. What about the `ldfserver-0.1.1.jar`, since it's using `war` packaging?

**Comment by hartig** [comment]
The WAR does not have the test classes either, and it is not available from the Maven repo. Again, these classes have been in the v0.1.0 JAR. Hence, you must have changed something such that they are not included any more. Did you move their JAVA files within the `src` directory?

BTW, you should increase the version number in the pom.xml.

**Comment by mielvds** [comment]
Yes, that was on purpose. However, I didn't realize I wasn't generating them anymore. I do now, but as a separate jar file, as is common practice. I'll update maven central (takes some time). Using it would be like this:

    <dependency>
      <groupId>org.linkeddatafragments</groupId>
      <artifactId>ldfserver</artifactId>
      <type>test-jar</type>
      <version>0.1.1</version>
      <scope>test</scope>
    </dependency>

Would that work for you?

**Comment by mielvds** [comment]
The jars seems to be in place: http://repo1.maven.org/maven2/org/linkeddatafragments/ldfserver/0.1.1/

**Comment by hartig** [comment]
Wow, you gave me a hard time by moving the test classes into a new package! It took me an hour to recognize this change and figure out that my builds were failing due to it. Anyways, now it is working :-)  Thanks for your help!
