### ISSUE TITLE
jena-3 or master branch ?

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Server.Java#35]
Just checking what the status of Jena 3 is :-) Master branch still uses Jena 2.x, while there is (was ?) some working going on in the Jena-3 branch. Is the latter still work in progress ?

**Comment by mielvds** [comment]
Right, yes, of course! now that the HDT repo has been upgraded, the server should be too.

**Comment by mielvds** [comment]
@hartig I'd like to sync this with your BlazeGraph datasource

**Comment by mielvds** [comment]
resolved in 23cc701da4e8eea3ae0a6c5944581e036095d6d4

**Comment by hartig** [comment]
@mielvds Was this just FYI or do you want me to do something?

**Comment by mielvds** [comment]
Fyi :) and a gentle encouragement to sync :) 
On Jul 5, 2016 20:56, Olaf Hartig <notifications@github.com> wrote:@mielvds Was this just FYI or do you want me to do something?

**Comment by hartig** [comment]
Thanks Miel. Understood ;-)   I will try to upgrade BlazegraphBasedTPFServer as soon as I find the time.
