### ISSUE TITLE
org.rdfhdt:hdt-jena version 2.0

### ISSUE THREAD

**Issue by smalyshev** [LinkedDataFragments/Server.Java#38]
The pom.xml file refers to jena HDT package version 2.0, but I only see 1.1 on maven:

http://mvnrepository.com/artifact/org.rdfhdt/hdt-jena

Is there newer package or special build instructions available to build it?

**Comment by mielvds** [comment]
That's right, you'll need to build 2.0 from source and install the jar in your local maven repo. No special instructions, the RDF/HDT github should have all the info.
