### ISSUE TITLE
ldfserver jar breaks JUnit

### ISSUE THREAD

**Issue by smalyshev** [LinkedDataFragments/Server.Java#39]
When trying to build a project that includes ldfserver jar (and thus depends on it), I get this error executing JUnit tests:

> Forked JVM's classpath must use JUnit 4.10 or newer.

This happens because the ldfserver jar contains an old copy of the class org.junit.runner.Description which is incompatible with new JUnit classes. 

In general, I don't think it's necessary to include the test classes into the jar, since they are not needed to run the server. It would be nice if Maven build binaries did not have these classes, or if they are necessary for running tests, had them in separate jar maybe.

**Comment by mielvds** [comment]
good suggestion! We're kind of swamped with other stuff right now, but always happy to accept pull requests ;)
