### ISSUE TITLE
Compilation fails, missing  MIMEParse

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Server.Java#4]
Running mvn install fails ("cannot find symbol" in src/org/linkeddatafragments/servlet/TriplePatternFragmentServlet.java)

It seems that the org.linkeddatafragments.util.MIMEParse util class wasn't pushed to the github.

**Comment by mielvds** [comment]
Your are absolutely right, my bad. Fixed in 0fa4d743fbad0fd18e54c5b9d12e01daeb9a7c94
