### ISSUE TITLE
Template error: “Expected a boolean, but this has evaluated to a number”

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedDataFragments/Server.Java#42]
https://query.wikidata.org/bigdata/ldf?subject=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ58596&object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ355304

**Comment by mielvds** [comment]
Seems like this is getting into a branch it shouldn't be in. Will try to reproduce, any HDT datadump?

**Comment by RubenVerborgh** [comment]
@smalyshev might be able to help you out.

**Comment by smalyshev** [comment]
This seems to happen every time when query returns no results. E.g. the same happens with:

https://query.wikidata.org/bigdata/ldf?subject=http://duck&object=http://duck

BTW, this one:

https://query.wikidata.org/bigdata/ldf?subject=duck

has even less informative error message.

**Comment by mielvds** [comment]
@smalyshev #43 is a step in the right direction. I'm not sure the last master branch fixes the issues though, still not able to reproduce. What datasource are you using?

**Comment by mielvds** [comment]
Try https://github.com/LinkedDataFragments/Server.Java/releases/tag/v0.2.1 and let me know

**Comment by smalyshev** [comment]
@mielvds I notice the version on this tag is still 0.2.0. Also, it requires org.rdfhdt:hdt-jena:jar:2.0 which doesn't seem to be in standard maven repos. I'll try to make a custom build or maybe backport the changes.

**Comment by mielvds** [comment]
Hi @smalyshev, I've updated the release. The missing artifact is normal, I don't control the maven repo unfortunately (See https://github.com/rdfhdt/hdt-java/issues/32). You'll have to manually build a jar and add it to your local maven repo.

**Comment by smalyshev** [comment]
The problem with URLs like this:

https://query.wikidata.org/bigdata/ldf?subject=http://duck&object=http://duck

seems to be fixed (don't look on query.wikidata.org yet, it's not deployed, but I did check on local build and it seems to provide good error message). This however:

https://query.wikidata.org/bigdata/ldf?subject=duck

still has just "duck" as error message. Not a huge deal but something more informative than repeating the input.

**Comment by mielvds** [comment]
So the strange thing is that I cannot reproduce the `?subject=duck` issue with an HDT datasource. This is probably an error message created in the BlazeGraph datasource from @hartig.

I'll close this issue for now, as the other issue seems to be resolved.
