### ISSUE TITLE
web.xml has references non-existent servlet AssetServlet

### ISSUE THREAD

**Issue by larsgsvensson** [LinkedDataFragments/Server.Java#50]
In web.xml I per chance found those entries
```xml
<servlet>
        <servlet-name>AssetServlet</servlet-name>
        <servlet-class>org.linkeddatafragments.servlet.AssetServlet</servlet-class>
</servlet>
```
and
```xml
<servlet-mapping>
        <servlet-name>AssetServlet</servlet-name>
        <url-pattern>/AssetServlet</url-pattern>
</servlet-mapping>
```
but there is no class `org.linkeddatafragments.servlet.AssetServlet`. Can those configs be removed?

**Comment by mielvds** [comment]
Good catch, these never even existed. Fixed in https://github.com/LinkedDataFragments/Server.Java/commit/f8ed4228c7f5afb6435b2d661a66592d577ffb21
