### ISSUE TITLE
SparqlDatasource is missing?

### ISSUE THREAD

**Issue by umairq** [LinkedDataFragments/Server.Java#51]
Hi:
I am testing for SparqlDatasource  but it seems missing? Is it not added yet?

**Comment by rubensworks** [comment]
SparqlDatasource is not supported in the Java version of the server AFAIK. It is however supported in the JavaScript version: https://github.com/LinkedDataFragments/Server.js

**Comment by umairq** [comment]
Thank you for your response, however, I have one more question.
I have tested on javascript version, it is giving correct output. But being a beginner in javascript, I want to change the output format, so it might output the total cardinality of the result triples and time of query execution. Is it possible? which file should I modify?
Thanks

**Comment by rubensworks** [comment]
> change the output format, so it might output the total cardinality of the result triples and time of query execution

Not sure, you might have to change a bunch of things then.
This might be a good starting point: https://github.com/LinkedDataFragments/Server.js/blob/develop/lib/datasources/SparqlDatasource.js

**Comment by umairq** [comment]
ok thankyou 👍
