### ISSUE TITLE
Jena TDB datasource

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Server.Java#7]
I'm working on a Jena TDB datasource.

Although the use case is perhaps a bit limited (AFAIK Jena does not like it when TDB is accessed by multiple applications, suggesting to use Fuseki instead... with of course additional overhead), I think it could be useful for serving data that is not updated frequently (e.g once a day).

Biggest problem is getting an estimate without doing a full count, so currently I just use `offset + size + 1`.

**Comment by RubenVerborgh** [comment]
Hi @barthanssens, that would be great!

However, as far as I understand, the first estimate for all triple patterns would then be `101` (given a page size of `100`)? This will not be sufficient for efficient query planning; some easy queries will take very long to execute.

**Comment by barthanssens** [comment]
I'll correct myself, the full logic would be:

* get a list of triples, with limit 100
* if the number of returned triples is less than 100, return `size` (e.g. 14), else assume there are more

**Comment by RubenVerborgh** [comment]
I see. Unfortunately, this will not produce a useful TPF for an executor. Estimations may be off, but it should be the case that count(a) << count(b) for typical a << b.

**Comment by barthanssens** [comment]
Yeah :-/

Other option would be to do a full count, but that would probably hurt performance on larger datasets (only guessing, didn't measure it), or try to get an estimate for Jena, but I'm not sure if that is available out-of-the box.

Perhaps using a third party module ? It seems that Parliament has developed something  
http://parliament.semwebcentral.org/javadoc/com/bbn/parliament/jena/query/index/pfunction/EstimableIndexPropertyFunction.html

**Comment by RubenVerborgh** [comment]
Most underlying implementations have _some_ way of doing approximate counts, as this is highly necessary metadata to execute any kind of query. There must be an interface that exposes this for Jena, but I don't know at which level. Full counts will indeed be slow.

**Comment by barthanssens** [comment]
This seems promising
https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/graph/GraphStatisticsHandler.html

**Comment by mielvds** [comment]
I believe Parliament is more performant than TDB, since it's more recent, partially C, and still under 'active' development. But I could be wrong. (The geo support might be interesting for the future though)

For Jena, you could give Model.getGraph().getStatisticsHandler() a shot. However, it could return -1 whenever no decent estimate is available (whatever that means), so be careful. @barthanssens I'm interested in such new datasource, so let me know if I can help

**Comment by mielvds** [comment]
Also, check out this: https://jena.apache.org/documentation/tdb/optimizer.html#statistics-rule-file

**Comment by barthanssens** [comment]
Currently looking into http://grepcode.com/file/repo1.maven.org/maven2/org.apache.jena/jena-tdb/0.10.1/com/hp/hpl/jena/tdb/solver/stats/Stats.java#Stats.gather%28com.hp.hpl.jena.graph.Graph%29

**Comment by mielvds** [comment]
Yes, seems like this only counts predicates and types: http://grepcode.com/file/repo1.maven.org/maven2/org.apache.jena/jena-tdb/0.10.1/com/hp/hpl/jena/tdb/solver/stats/StatsCollectorBase.java#42

Can you inject a custom implementation?

**Comment by barthanssens** [comment]
I'll give it a try, but no guarantees :-)

**Comment by barthanssens** [comment]
Maybe a silly idea, but perhaps a separate statistics class might come in handy. It appears to me that optimizers and jena and e.g. sesame use "cost" metrics (not necessarily "amount of triples", although one can specify the number of triples in the tdbstats, but I don't think it scales well if one wants to record statistics for millions triples).

So what about a tool that generates stats info (not unlike jena's) that parsers the triple store, calculates the number of different S, number of different P and some combinations / distributions etc and stores it to one or more files. Those files can be added to the configuration of the datasource, and be read once and kept in memory to calculate a somewhat reasonable estimate.

**Comment by mielvds** [comment]
Yeah, a statistics index. No way around it I'm afraid

**Comment by mielvds** [comment]
In fact, it has triple pattern estimation: http://rdfstats.sourceforge.net/#api

**Comment by mielvds** [comment]
Fixed in #11
